version: '3.7'

services:

  web:
    build: ./deals_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./deals_api/:/usr/src/deals_api/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=deals_api
      - POSTGRES_PASSWORD=deals_api
      - POSTGRES_DB=deals_api
volumes:
  postgres_data: