version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    hostname: db
    container_name: 'deals_api_postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=deals_api
      - POSTGRES_PASSWORD=deals_api
      - POSTGRES_DB=deals_api
  web:
    build: ./deals_api
    container_name: 'deals_api_django'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./deals_api/:/usr/src/deals_api/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery:
    build: ./deals_api
    command: celery worker --app=deals_api --loglevel=info
    volumes:
      - ./deals_api:/usr/src/deals_api/
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  dashboard:
    build: ./deals_api
    command: flower -A deals_api --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery
  redis:
    image: redis:alpine
    hostname: redis
    container_name: 'deals_api_redis'
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379
volumes:
  postgres_data: