version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    container_name: 'deals_api_postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./deals_api
      dockerfile: Dockerfile.prod
    command: gunicorn deals_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/deals_api/web/staticfiles
      - media_volume:/home/deals_api/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  celery:
    build: ./deals_api
    command: celery worker --app=deals_api --loglevel=info
    volumes:
      - ./deals_api:/usr/src/deals_api/
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  dashboard:
    build: ./deals_api
    command: flower -A deals_api --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery
  nginx:
    build: ./nginx
    container_name: 'deals_api_nginx'
    volumes:
      - static_volume:/home/deals_api/web/staticfiles
      - media_volume:/home/deals_api/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:alpine
    hostname: redis
    container_name: 'deals_api_redis'
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379

volumes:
  postgres_data:
  static_volume:
  media_volume: